### PR TITLE
added wpbf_before_loop and wpbf_after_loop to page.php

### PR DESCRIPTION
**Pull request by gbruzzo**

### CODE REVIEW

**Comment by gbruzzo** [comment]
Hi there! 

As suggested, I did a pull request - I added the wpbf_before_loop and wpbf_after_loop hooks to both page-sidebar.php and page.php. 

Could you make them accessible in custom sections  as well? 

If that is not possible (it was mentioned that these hooks are 'internal'), would you consider adding a further set of before/after 'accessible' hooks (just before and after the loop as well,  but accessible, also in custom sections). They are really useful there, because they sit inside 

```
<main id="main" class="wpbf-main wpbf-medium-2-3>
....
....
</main>
```
as such inherit all formatting etc from that class etc. 
One area would sit above the content, one below, but to the side of the sidebar. 

thank you in advance 

Giacomo Bruzzo

**Comment by mapsteps** [comment]
Hi @gbruzzo,

We're leaving out the single.php here.

The single.php already has hooks in that area (`wpbf_before_article` & `wpbf_after_article`).

To keep things consistent, we need to have a closer look at this.

I think we can do 2 things.

Either:

add hooks like `wpbf_main_open` & `wpbf_main_close` to all files (archives, page.php, single.php, etc.).

Downside:
- This would result in 2 different hooks in single.php at the exact same position.
- The hooks ar not descriptive

These hooks would affect all types of pages (archives, posts & pages) at the same time. I think this can be seen as a downside or upside, depending on what the user is trying to achive.

OR (what I think I'd prefer):

add `wpbf_before_loop` & `wpbf_after_loop` to custom sections and add more specific hooks to `page.php` and `page-sidebar.php` - just like we do it for `single.php`.

in single.php we have hooks right after the opening `<main>` and right before the closing `</main>` element (`wpbf_before_article` & `wpbf_after_article`).

What if we add something like `wpbf_before_page` & `wpbf_after_page` to `page.php` & `page-sidebar.php`?

With that, we'd maintain consistency and differentiate between pages, posts & archives. As mentioned above, I can see how global hooks that affect all types of pages can make sense too but since we've done this before fore the `single.php`, this looks like the best approach to me.

Let me know what you think.

**Comment by gbruzzo** [comment]
Hello @MapSteps, thanks for your answer.

Premise : My main concern is the _placement_ of the new open/close hooks and their _availability_ for custom sections in the premium plugin. I am less concerned by them not having the same name across different templates, though I wholly understand the need for lexical order and the avoidance of duplication. Your theme is predicated upon simplicity, but you also  strive for generality of application, which may lead to code bloat - it is a very difficult tradeoff to manage.

Recapping, we'd love to see 

- placement of new open/close hooks inside `<main></main>` class 
- availability of these on pages (with / without sidebar), single posts (for custom posts principally), on post/custom post archives (hopefully including Woocommerce products), maybe with different names

The reason for this is to have 3 opening hooks and 3 closing hooks to **bolt custom sections onto**. 
 
2 (4 in total) of these are bolted onto above/below  content/inner content (sitting _**above**_ sidebars) (these hooks already exist, are accessible via custom sections, and are the same across all templates) 

1 (2 in total) bolted onto this new hook above/below loop (sitting _**within**_ sidebars)
(3 above, 3 below).  These are the 'new' hooks.

We currently use Widget Options/Widget Areas to create widget positions and assign these widget positions to custom sections (via shortcodes) (for the first 4) 
We are using a Generic Wordpress Hook (above/below content) in conjunction with Widget Options/Windget Areas as a replacement for the new hooks we are hoping you will implement. 

=> We strive to _**reduce**_ this layer of complication, as we would like to remove our dependency from Widget Options/Areas and replace them with Custom Sections (for the Logic) and  **_Gutenberg Blocks_**, once we find a family of blocks to replace Yootheme's Widgetkit) and if we manage to convince the developer of acfwidgets to convert them to Blocks. 

Ideally. The custom sections will bear all the Widget Logic (place here if / then etc), and we will have removed one layer of complication. This explains our motives. 

So: 

If I understand correctly, you propose 

- `wpbf_before_loop & wpbf_after_loop` on archive.php/index.php/search.php
- `wpbf_before_article & wpbf_after_article` on single.php
- `wpbf_before_page & wpbf_after_page` on page.php / page-sidebar.php

perfectly fine for us, if accessible via custom sections. 


Giacomo Bruzzo

**Comment by mapsteps** [comment]
Hey @gbruzzo,

exactly. I'm actually working on a website right now where I need hooks in the exact same place. 

I'm probably overthinking this (a lot) - but what do you think is better?

doing something like:


- `wpbf_before_loop & wpbf_after_loop` on archive.php/index.php/search.php
- `wpbf_before_article & wpbf_after_article` on single.php
- `wpbf_before_page & wpbf_after_page` on page.php / page-sidebar.php

or adding

- `wpbf_main_open`
- and `wpbf_main_close`

to all files?

**Comment by gbruzzo** [comment]
Hello @mapsteps

From my own perspective, I believe it would make no practical difference,
in as much as one can then use either widget logic or eventually your
custom section logic to target a particular type of post / page / archive

Having the same name across different templates would make it easier to
explain their use to customers and might help you sustain the notion of a
uniformity coupled with flexibility.

**Comment by mapsteps** [comment]
Done! :) 6fd4b90b018a7346411c0096120b853f021e933e

**Comment by gbruzzo** [comment]
Dear @MapSteps 

do you have a roadmap for when the new hooks will be available to select in the premium plugin? 

Thank you in advance 

Giacomo Bruzzo

**Comment by mapsteps** [comment]
Hi @gbruzzo,

The new hooks are now available in Custom Sections. We've released 2.0.4 of the Premium Add-On today :)

Best,
David

**Comment by gbruzzo** [comment]
Installed everything @mapsteps, all works GREAT!!

Thank you

**Pull request closed without merging**
